# Generated by Django 4.0.6 on 2022-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctionlisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Add a description for the listing.')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.URLField(max_length=500)),
            ],
        ),
    ]
