# Generated by Django 4.0.6 on 2022-07-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='current_price',
            new_name='starting_bid',
        ),
    ]
