# Generated by Django 4.0.6 on 2022-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_current_price_auctionlisting_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='photo',
            field=models.URLField(blank=True, help_text='Optionally provide a URL for an image for the listing', max_length=500),
        ),
    ]
