# Generated by Django 4.0.6 on 2022-07-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auctionlisting',
            new_name='Listing',
        ),
    ]
