# Generated by Django 4.0.6 on 2022-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_listingdetails_listingdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingdetail',
            name='categories',
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.category'),
        ),
    ]
