# Generated by Django 4.0.6 on 2022-07-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listingdetail_categories_listing_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.listing'),
        ),
    ]
