# Generated by Django 4.0.6 on 2022-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listingdetail_all_bids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingdetail',
            name='all_bids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
