# Generated by Django 4.0.6 on 2022-07-16 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listingdetail_all_bids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingdetail',
            name='all_bids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingdetail',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
