# Generated by Django 4.0.6 on 2022-08-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listingdetail_all_bids_listing_active_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
    ]
