# Generated by Django 4.0.6 on 2022-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_bid_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingdetail',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
