# Generated by Django 4.0.6 on 2022-08-03 11:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listingdetail_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingdetail',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='listingdetail',
            name='highest_bidder',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
